// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKClQk1tTN2BcWunnYT1LzOb5ObTmc2e4',
    appId: '1:548728610706:web:5cc308b73c86499118eb4b',
    messagingSenderId: '548728610706',
    projectId: 'favo-bdb08',
    authDomain: 'favo-bdb08.firebaseapp.com',
    storageBucket: 'favo-bdb08.firebasestorage.app',
    measurementId: 'G-1RHZDRD2F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlvoGYus1drsof1jYGjxYzeeI7kGOyM64',
    appId: '1:548728610706:android:82b981f0a1979e9818eb4b',
    messagingSenderId: '548728610706',
    projectId: 'favo-bdb08',
    storageBucket: 'favo-bdb08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjKLmx-DZ9JqMjfDU1zYNbWTBkCcxbRJg',
    appId: '1:548728610706:ios:887a89890f67ea6f18eb4b',
    messagingSenderId: '548728610706',
    projectId: 'favo-bdb08',
    storageBucket: 'favo-bdb08.firebasestorage.app',
    iosBundleId: 'com.example.favoMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjKLmx-DZ9JqMjfDU1zYNbWTBkCcxbRJg',
    appId: '1:548728610706:ios:887a89890f67ea6f18eb4b',
    messagingSenderId: '548728610706',
    projectId: 'favo-bdb08',
    storageBucket: 'favo-bdb08.firebasestorage.app',
    iosBundleId: 'com.example.favoMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKClQk1tTN2BcWunnYT1LzOb5ObTmc2e4',
    appId: '1:548728610706:web:8ac79260211627db18eb4b',
    messagingSenderId: '548728610706',
    projectId: 'favo-bdb08',
    authDomain: 'favo-bdb08.firebaseapp.com',
    storageBucket: 'favo-bdb08.firebasestorage.app',
    measurementId: 'G-TZ2F95NM7L',
  );

}